import type { Metadata } from 'next'
import { Be_Vietnam_Pro as bevietnam } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'

const vietnamese = bevietnam({
  subsets: ['vietnamese'],
  weight: ['600','100', "700", "800", "900"]
})

export const metadata: Metadata = {
  title: 'World Rank',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(vietnamese.className, "w-full bg-pbg h-screen overflow-x-hidden")} >
        <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
